// LinkedIn Industry Codes (V2 for Sales Navigator, V1 for Classic)
// Source: Microsoft / LinkedIn Documentation (Approximate comprehensive list)

// Classic Industry Codes (V1) - ~149 industries
// Used for "classic" search
const INDUSTRY_V1 = [
  { id: "47", title: "Accounting" },
  { id: "94", title: "Airlines/Aviation" },
  { id: "120", title: "Alternative Dispute Resolution" },
  { id: "125", title: "Alternative Medicine" },
  { id: "127", title: "Animation" },
  { id: "19", title: "Apparel & Fashion" },
  { id: "50", title: "Architecture & Planning" },
  { id: "111", title: "Arts and Crafts" },
  { id: "53", title: "Automotive" },
  { id: "52", title: "Aviation & Aerospace" },
  { id: "41", title: "Banking" },
  { id: "12", title: "Biotechnology" },
  { id: "36", title: "Broadcast Media" },
  { id: "49", title: "Building Materials" },
  { id: "138", title: "Business Supplies and Equipment" },
  { id: "129", title: "Capital Markets" },
  { id: "54", title: "Chemicals" },
  { id: "90", title: "Civic & Social Organization" },
  { id: "51", title: "Civil Engineering" },
  { id: "128", title: "Commercial Real Estate" },
  { id: "118", title: "Computer & Network Security" },
  { id: "109", title: "Computer Games" },
  { id: "3", title: "Computer Hardware" },
  { id: "5", title: "Computer Networking" },
  { id: "4", title: "Computer Software" },
  { id: "48", title: "Construction" },
  { id: "24", title: "Consumer Electronics" },
  { id: "25", title: "Consumer Goods" },
  { id: "91", title: "Consumer Services" },
  { id: "18", title: "Cosmetics" },
  { id: "65", title: "Dairy" },
  { id: "1", title: "Defense & Space" },
  { id: "99", title: "Design" },
  { id: "69", title: "Education Management" },
  { id: "132", title: "E-Learning" },
  { id: "112", title: "Electrical/Electronic Manufacturing" },
  { id: "28", title: "Entertainment" },
  { id: "86", title: "Environmental Services" },
  { id: "110", title: "Events Services" },
  { id: "76", title: "Executive Office" },
  { id: "122", title: "Facilities Services" },
  { id: "63", title: "Farming" },
  { id: "43", title: "Financial Services" },
  { id: "38", title: "Fine Art" },
  { id: "66", title: "Fishery" },
  { id: "34", title: "Food & Beverages" },
  { id: "23", title: "Food Production" },
  { id: "101", title: "Fund-Raising" },
  { id: "26", title: "Furniture" },
  { id: "29", title: "Gambling & Casinos" },
  { id: "145", title: "Glass, Ceramics & Concrete" },
  { id: "75", title: "Government Administration" },
  { id: "148", title: "Government Relations" },
  { id: "140", title: "Graphic Design" },
  { id: "124", title: "Health, Wellness and Fitness" },
  { id: "68", title: "Higher Education" },
  { id: "14", title: "Hospital & Health Care" },
  { id: "31", title: "Hospitality" },
  { id: "137", title: "Human Resources" },
  { id: "134", title: "Import and Export" },
  { id: "88", title: "Individual & Family Services" },
  { id: "147", title: "Industrial Automation" },
  { id: "84", title: "Information Services" },
  { id: "96", title: "Information Technology and Services" },
  { id: "42", title: "Insurance" },
  { id: "74", title: "International Affairs" },
  { id: "141", title: "International Trade and Development" },
  { id: "6", title: "Internet" },
  { id: "45", title: "Investment Banking" },
  { id: "46", title: "Investment Management" },
  { id: "73", title: "Judiciary" },
  { id: "77", title: "Law Enforcement" },
  { id: "9", title: "Law Practice" },
  { id: "10", title: "Legal Services" },
  { id: "72", title: "Legislative Office" },
  { id: "30", title: "Leisure, Travel & Tourism" },
  { id: "85", title: "Libraries" },
  { id: "116", title: "Logistics and Supply Chain" },
  { id: "143", title: "Luxury Goods & Jewelry" },
  { id: "55", title: "Machinery" },
  { id: "11", title: "Management Consulting" },
  { id: "95", title: "Maritime" },
  { id: "97", title: "Market Research" },
  { id: "80", title: "Marketing and Advertising" },
  { id: "135", title: "Mechanical or Industrial Engineering" },
  { id: "126", title: "Media Production" },
  { id: "17", title: "Medical Devices" },
  { id: "13", title: "Medical Practice" },
  { id: "139", title: "Mental Health Care" },
  { id: "71", title: "Military" },
  { id: "56", title: "Mining & Metals" },
  { id: "35", title: "Motion Pictures and Film" },
  { id: "37", title: "Museums and Institutions" },
  { id: "115", title: "Music" },
  { id: "114", title: "Nanotechnology" },
  { id: "81", title: "Newspapers" },
  { id: "100", title: "Non-Profit Organization Management" },
  { id: "57", title: "Oil & Energy" },
  { id: "113", title: "Online Media" },
  { id: "123", title: "Outsourcing/Offshoring" },
  { id: "87", title: "Package/Freight Delivery" },
  { id: "146", title: "Packaging and Containers" },
  { id: "61", title: "Paper & Forest Products" },
  { id: "39", title: "Performing Arts" },
  { id: "15", title: "Pharmaceuticals" },
  { id: "131", title: "Philanthropy" },
  { id: "136", title: "Photography" },
  { id: "117", title: "Plastics" },
  { id: "107", title: "Political Organization" },
  { id: "67", title: "Primary/Secondary Education" },
  { id: "83", title: "Printing" },
  { id: "105", title: "Professional Training & Coaching" },
  { id: "102", title: "Program Development" },
  { id: "79", title: "Public Policy" },
  { id: "98", title: "Public Relations and Communications" },
  { id: "78", title: "Public Safety" },
  { id: "82", title: "Publishing" },
  { id: "62", title: "Railroad Manufacture" },
  { id: "64", title: "Ranching" },
  { id: "44", title: "Real Estate" },
  { id: "40", title: "Recreational Facilities and Services" },
  { id: "89", title: "Religious Institutions" },
  { id: "144", title: "Renewables & Environment" },
  { id: "70", title: "Research" },
  { id: "32", title: "Restaurants" },
  { id: "27", title: "Retail" },
  { id: "121", title: "Security and Investigations" },
  { id: "7", title: "Semiconductors" },
  { id: "58", title: "Shipbuilding" },
  { id: "20", title: "Sporting Goods" },
  { id: "33", title: "Sports" },
  { id: "104", title: "Staffing and Recruiting" },
  { id: "22", title: "Supermarkets" },
  { id: "8", title: "Telecommunications" },
  { id: "60", title: "Textiles" },
  { id: "130", title: "Think Tanks" },
  { id: "21", title: "Tobacco" },
  { id: "108", title: "Translation and Localization" },
  { id: "92", title: "Transportation/Trucking/Railroad" },
  { id: "59", title: "Utilities" },
  { id: "106", title: "Venture Capital & Private Equity" },
  { id: "16", title: "Veterinary" },
  { id: "93", title: "Warehousing" },
  { id: "133", title: "Wholesale" },
  { id: "142", title: "Wine and Spirits" },
  { id: "119", title: "Wireless" },
  { id: "103", title: "Writing and Editing" },
];

// Sales Navigator Industry Codes (V2) - Categorized
// Used for "sales_navigator" and "recruiter" search
// These align closer to NAICS
const INDUSTRY_V2 = [
  // Technology, Information and Media
  { id: "6", title: "Technology, Information and Internet" },
  { id: "4", title: "Software Development" },
  { id: "96", title: "IT Services and IT Consulting" },
  { id: "118", title: "Computer and Network Security" },
  { id: "3", title: "Computer Hardware Manufacturing" },
  { id: "5", title: "Computer Networking Products" },
  { id: "7", title: "Semiconductor Manufacturing" },
  { id: "8", title: "Telecommunications" },
  { id: "119", title: "Wireless Services" },
  { id: "109", title: "Computer Games" },
  { id: "113", title: "Online Audio and Video Media" },
  { id: "82", title: "Book and Periodical Publishing" },
  { id: "36", title: "Broadcast Media Production and Distribution" },
  { id: "84", title: "Information Services" },
  { id: "126", title: "Media Production" },

  // Financial Services
  { id: "43", title: "Financial Services" },
  { id: "41", title: "Banking" },
  { id: "45", title: "Investment Banking" },
  { id: "46", title: "Investment Management" },
  { id: "42", title: "Insurance" },
  { id: "129", title: "Capital Markets" },
  { id: "106", title: "Venture Capital and Private Equity Principals" },
  { id: "47", title: "Accounting" },

  // Professional Services
  { id: "11", title: "Business Consulting and Services" },
  { id: "104", title: "Staffing and Recruiting" },
  { id: "137", title: "Human Resources Services" },
  { id: "80", title: "Advertising Services" },
  { id: "97", title: "Market Research" },
  { id: "98", title: "Public Relations and Communications Services" },
  { id: "9", title: "Law Practice" },
  { id: "10", title: "Legal Services" },
  { id: "99", title: "Design Services" },
  { id: "50", title: "Architecture and Planning" },
  { id: "51", title: "Civil Engineering" },

  // Manufacturing & Industrial
  { id: "147", title: "Industrial Machinery Manufacturing" },
  { id: "145", title: "Glass, Ceramics and Concrete Manufacturing" },
  { id: "112", title: "Appliances, Electrical, and Electronics Manufacturing" },
  { id: "53", title: "Motor Vehicle Manufacturing" },
  { id: "52", title: "Aviation and Aerospace Component Manufacturing" },
  { id: "15", title: "Pharmaceutical Manufacturing" },
  { id: "17", title: "Medical Equipment Manufacturing" },
  { id: "12", title: "Biotechnology Research" },
  { id: "54", title: "Chemical Manufacturing" },
  { id: "117", title: "Plastics Manufacturing" },
  { id: "57", title: "Oil and Gas" },
  { id: "56", title: "Mining" },
  { id: "144", title: "Renewable Energy Semiconductor Manufacturing" },
  { id: "59", title: "Utilities" },
  { id: "48", title: "Construction" },

  // Retail & Consumer
  { id: "27", title: "Retail" },
  { id: "25", title: "Consumer Goods" },
  { id: "34", title: "Food and Beverage Services" },
  { id: "31", title: "Hospitality" },
  { id: "32", title: "Restaurants" },
  { id: "19", title: "Retail Apparel and Fashion" },
  { id: "24", title: "Computers and Electronics Retail" },
  { id: "133", title: "Wholesale" },
  { id: "22", title: "Retail Groceries" },
  { id: "26", title: "Furniture and Home Furnishings Manufacturing" },
  { id: "18", title: "Personal Care Product Manufacturing" },
  { id: "20", title: "Sporting Goods Manufacturing" },

  // Healthcare
  { id: "14", title: "Hospitals and Health Care" },
  { id: "13", title: "Medical Practices" },
  { id: "139", title: "Mental Health Care" },
  { id: "124", title: "Wellness and Fitness Services" },
  { id: "16", title: "Veterinary Services" },

  // Education & Government
  { id: "69", title: "Education Administration Programs" },
  { id: "68", title: "Higher Education" },
  { id: "67", title: "Primary and Secondary Education" },
  { id: "132", title: "E-Learning Providers" },
  { id: "75", title: "Government Administration" },
  { id: "1", title: "Defense and Space Manufacturing" },
  { id: "74", title: "International Affairs" },
  { id: "90", title: "Civic and Social Organizations" },
  { id: "100", title: "Non-profit Organizations" },
  { id: "131", title: "Philanthropic Fundraising Services" },

  // Transportation & Logistics
  { id: "92", title: "Transportation, Logistics, Supply Chain and Storage" },
  { id: "94", title: "Airlines and Aviation" },
  { id: "95", title: "Maritime Transportation" },
  { id: "116", title: "Truck Transportation" },
  { id: "87", title: "Freight and Package Transportation" },
  { id: "62", title: "Railroad Equipment Manufacturing" },

  // Real Estate
  { id: "44", title: "Real Estate" },
  { id: "128", title: "Commercial Real Estate" },
];

module.exports = {
  INDUSTRY_V1,
  INDUSTRY_V2,
};
